version: "3.9"

services:
    postgres:
        container_name: postgres
        image: postgres:15-alpine
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./tmp/pgdata:/var/lib/postgresql/data
        networks:
            - wombaNet

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
        ports:
            - "${PGADMIN_EXTERNAL_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}"
        volumes:
            - pgadmin-store:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - wombaNet

    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
                CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
        environment:
            - CLIENT_PORT=${CLIENT_PORT}
            - SERVER_PORT=${SERVER_PORT}
        depends_on:
            - postgres
            - server
        networks:
            - wombaNet
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
                SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
            SERVER_PORT: ${SERVER_PORT}
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - wombaNet

volumes:
    pgadmin-store:

networks:
    wombaNet:
        driver: bridge
