name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    #needs: [ build-and-push ]
    runs-on: ubuntu-latest

    steps:
      - name: Copy docker-compose.yml
        uses: garygrossgarten/github-action-scp@release
        with:
          local: docker-compose.yml
          remote: /var/snap/docker-compose.yml
          host: 62.84.123.70
          username: dda
          port: 22
          privateKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL4RRNpTcgMW910Qy9xkFCRAMNCStmZhRd6uHPZo2BwE daniladenisov@daniladenisov-o'
