name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    #needs: [ build-and-push ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy docker-compose.yml
        uses: garygrossgarten/github-action-scp@release
        with:
          local: docker-compose.yml
          remote: ${{ vars.DEPLOY_PATH }}/docker-compose.yml
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          privateKey: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Copy .env
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .env.sample
          remote: ${{ vars.DEPLOY_PATH }}/.env
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          privateKey: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Pull and start womba
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin cr.yandex
            cd ${{ vars.DEPLOY_PATH }}
            docker-compose pull -f ${{ vars.DEPLOY_PATH }}/docker-compose.yml
            docker-compose up nginx server postgres
            docker system prune -af
